package mythermostat.thermostat;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import mythermostat.ITimer;
import mythermostat.ITimerCallback;
import mythermostat.thermostat.IThermostatStatemachine.SCInterfaceOperationCallback;
import mythermostat.thermostat.ThermostatStatemachine.State;

/**
 * Unit tests for the core {@link ThermostatStatemachine} logic, generated by
 * YAKINDU. A no-op {@link ITimer} double is used so that state transitions
 * are driven deterministically by explicit raise*()/runCycle() calls instead
 * of relying on real background timers. Every test here starts from a fully
 * entered machine; see {@link ThermostatStatemachineLifecycleTest} for
 * pre-init/pre-enter behavior.
 */
class ThermostatStatemachineTest {

	/** ITimer double that never actually schedules anything. */
	private static class NoOpTimer implements ITimer {
		@Override
		public void setTimer(ITimerCallback callback, int eventID, long time, boolean isPeriodic) {
			// intentionally does nothing: tests drive transitions explicitly
		}

		@Override
		public void unsetTimer(ITimerCallback callback, int eventID) {
			// intentionally does nothing
		}
	}

	private ThermostatStatemachine therm;

	@BeforeEach
	void setUp() {
		therm = new ThermostatStatemachine();
		therm.setTimer(new NoOpTimer());
		SCInterfaceOperationCallback outTempCallback = () -> 5L;
		therm.getSCInterface().setSCInterfaceOperationCallback(outTempCallback);
		therm.init();
		therm.enter();
	}

	// Verifies that enter() activates the statemachine and puts it into its
	// expected initial composite state: controller Off, window Closed, and the
	// seconds-increment timer state, with the On state not yet active.
	@Test
	void enterActivatesDefaultStates() {
		assertTrue(therm.isActive());
		assertTrue(therm.isStateActive(State.controller_Status_r1_Off));
		assertTrue(therm.isStateActive(State.window_Closed));
		assertTrue(therm.isStateActive(State.timer_IncrementSeconds));
		assertFalse(therm.isStateActive(State.controller_Status_r1_On));
	}

	// Verifies that raising the Mode event while the controller is Off
	// transitions it to the On state.
	@Test
	void raiseModeTurnsThermostatOnFromOff() {
		therm.raiseMode();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.controller_Status_r1_On));
		assertFalse(therm.isStateActive(State.controller_Status_r1_Off));
	}

	// Verifies that at the default hour (0, before "day" starts at 8), turning
	// the thermostat on settles it into the Night sub-state after one extra cycle.
	@Test
	void turningOnAtDefaultHourSettlesIntoNightSubState() {
		therm.raiseMode();
		therm.runCycle();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.controller_Status_r1_On_r1_Night));
	}

	// Verifies that raising OpenWindow while the controller is On pauses it:
	// the window state becomes Open, getIsOpen() reports true, and the
	// controller enters the Pause state.
	@Test
	void openingWindowPausesAnActiveThermostat() {
		therm.raiseMode();
		therm.runCycle();
		// Run one more cycle so the Day/Night sub-state settles and the On state
		// is stable before checking the openWindow reaction (see
		// turningOnAtDefaultHourSettlesIntoNightSubState for that settling behavior).
		therm.runCycle();

		therm.raiseOpenWindow();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.window_Open));
		assertTrue(therm.getIsOpen());
		assertTrue(therm.isStateActive(State.controller_Status_r1_Pause));
	}

	// Verifies that raising CloseWindow after a window-triggered pause resumes
	// normal operation: the window state becomes Closed, getIsOpen() reports
	// false, and the controller returns to On (no longer Pause).
	@Test
	void closingWindowResumesFromPause() {
		therm.raiseMode();
		therm.runCycle();
		therm.runCycle();
		therm.raiseOpenWindow();
		therm.runCycle();

		therm.raiseCloseWindow();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.window_Closed));
		assertFalse(therm.getIsOpen());
		assertTrue(therm.isStateActive(State.controller_Status_r1_On));
		assertFalse(therm.isStateActive(State.controller_Status_r1_Pause));
	}

	// Verifies that raising Set from the Off state enters the day-temperature
	// setting screen.
	@Test
	void raiseSetFromOffEntersSetDayTemperatureScreen() {
		therm.raiseSet();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.controller_Settings_r1_SetDayTemperature));
	}

	// Verifies that raising Mode while on the day-temperature setting screen
	// lowers the day temperature down to the configured minimum bound.
	@Test
	void raiseModeInSetDayTemperatureScreenLowersDayTemperatureToMinimum() {
		therm.raiseSet();
		therm.runCycle();

		therm.raiseMode();
		therm.runCycle();

		assertEquals(therm.getMinT(), therm.getDayT());
	}

	// Verifies that raising Set again while on the day-temperature setting
	// screen advances to the night-temperature setting screen.
	@Test
	void raiseSetInSetDayTemperatureScreenAdvancesToSetNightTemperatureScreen() {
		therm.raiseSet();
		therm.runCycle();
		therm.raiseMode();
		therm.runCycle();

		therm.raiseSet();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.controller_Settings_r1_SetNightTemperature));
	}

	// Verifies that raising Set while on the night-temperature setting screen
	// exits the Settings menu back to the Off state.
	@Test
	void raiseSetInSetNightTemperatureScreenReturnsToOff() {
		therm.raiseSet();
		therm.runCycle();
		therm.raiseMode();
		therm.runCycle();
		therm.raiseSet();
		therm.runCycle();

		therm.raiseSet();
		therm.runCycle();

		assertTrue(therm.isStateActive(State.controller_Status_r1_Off));
	}
}
